### ISSUE TITLE
Uwagi

### ISSUE THREAD

**Issue by MarcinCiura** [ksonax/Python-Sorting-Algorithms-Visualization#1]
1. Katalog `idea` do wyrzucenia (1. rozdział Poradnika).
2. `Python.gitignore` nic nie robi pod taką nazwą. Przenieść do `.gitignore`.
3. Zagadka: co się stanie, kiedy Pan uruchomi `pip install -r requirements.txt`? Przeczytać 1. rozdział.
4. Importy tak (2. rozdział):
```python
import random
import pygame
import pygame_gui
```
5. `pygame.init()` itp. do `main()` (3. rozdział).
6. [Te klawisze też](https://github.com/ksonax/Python-Sorting-Algorithms-Visualization/blob/c9ac7b75c37ddc7497dbcf2243601909cc824c96/main.py#L33).
7. Za długie wiersze podzielić (2. rozdział).
8. [To wywołanie też](https://github.com/ksonax/Python-Sorting-Algorithms-Visualization/blob/c9ac7b75c37ddc7497dbcf2243601909cc824c96/main.py#L48).
9. Nie używamy skrótów (arr)
10. Powstawiać puste wiersze między zduszone funkcje.
11. Podopisywać do funkcji docstringi (2. rozdział). Czy uruchamiał Pan pylinta, tak w ogóle? Nie musiałbym pisać połowy tych uwag.
12. [`RUN`](https://github.com/ksonax/Python-Sorting-Algorithms-Visualization/blob/c9ac7b75c37ddc7497dbcf2243601909cc824c96/main.py#L193) to zły styl nazwy (2. rozdział). Pylint!
13. [Naprawdę nie trzeba](https://github.com/ksonax/Python-Sorting-Algorithms-Visualization/blob/c9ac7b75c37ddc7497dbcf2243601909cc824c96/main.py#L201) powtarzać tych dwóch wierszy *N* razy. Wystarczy raz.
14. Koniec pliku przerobić zgodnie z 3. rozdziałem.
15. [Kolory](https://github.com/ksonax/Python-Sorting-Algorithms-Visualization/blob/c9ac7b75c37ddc7497dbcf2243601909cc824c96/main.py#L3) ponazywać zgodnie z zastosowaniem, a nie zawartością (2. rozdział). Nadto przeczytać narzekanie na kolory (3. rozdział).
16. Shellsort z dzieleniem odstępów na pół jest do bani. Proszę użyć stałej listy odstępów: `[1, 4, 10, 23, 57]`. Może Pan ją zapisać w programie wspak, jeśli tak będzie wygodniej.

**Comment by ksonax** [comment]
Poprawiono kod według uwag.
Dodano klasę "TimeDelay" która przetrzymuję wartości opóźnienia w odświeżaniu ekranu, dla każdej z metod sortowania. Teraz każda metoda wykonuje się w odpowiednim czasie.
Przyciski GUI zostały przeniesione do maina i teraz tworzone są w pętli (wcześniej typowe kopiuj-wklej)

**Comment by MarcinCiura** [comment]
Dziękuję za zmiany. Oto kolejna porcja uwag.
1. `TestColors` wyrzucić, bo naprawdę nic odkrywczego nie robi.
2. W `TestFunctions` zrobić
```python
def setUp(self):
    self.test_array = ...
    self.correctly_sorted_array = sorted(self.test_array)
```
i powyrzucać, co teraz niepotrzebne, z metod.
3. [Tu](https://github.com/ksonax/Python-Sorting-Algorithms-Visualization/blob/ad48837bc1f3a26351e65f9c3ce6596231daddca/testy.py#L33) i wszędzie użyć `assertEqual(self.test_array, self.correctly_sorted_array)`.
4. `testy.py` przemianować na `main_test.py`. Nadto posortować importy (2. rozdział).
5. Powtarzam: czy te kolory naprawdę muszą być takie prymitywne? (3. rozdział).

**Comment by ksonax** [comment]
Poprawki zostały naniesione.
Kolory teraz nazwane są według ich zastosowania w programie.

**Comment by MarcinCiura** [comment]
Dziękuję za zmiany. LGTM, jest Pan trzydziesty czwarty.
